MardisGeo/Controllers/VisualizadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MardisGeo.Views.modelWeb;
using GeoMardis.Model.Categorias;
using MardisGeo.bussiness.Categoria;
using Microsoft.AspNetCore.Mvc.Rendering;
using MardisGeo.bussiness.Secuencia;
using MardisGeo.bussiness.Geo;
using System.Text;
using System.IO;
using System.Drawing;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.DotNet.PlatformAbstractions;

namespace MardisGeo.Controllers
{
    public class VisualizadorController : Controller
    {

        private string ValUsuario=null;
        private ICategoria categoria = new ICategoria();
        private Secuencial secuencial = new Secuencial();
        private Geofoto foto = new Geofoto();
        private SaveGeoUbicacion geoUbicacion = new SaveGeoUbicacion();
        // GET: Visualizador
        public ActionResult Index()
        {
            ValUsuario = HttpContext.Session.GetString("IsUsuario");
         
            if (ValUsuario != null)
            {

                IList<ListModel> lstCategoria = new List<ListModel>();
                IList<geo_categoria> structCategoria = new List<geo_categoria>();
              
                var strucCategoria = categoria.CategoriasActivas();
                var d = (from x in strucCategoria
                               select new { Id = x.id, Text = x.Name});
                SelectList slCategoria = new SelectList(d, "Id", "Text");
                ViewBag.slCategoria = slCategoria;
              
                
                    ViewBag.lgnUsuario = ValUsuario;
                return View();
            }
            else {
                return RedirectToAction("logout", "Login");

            }
            
        }

        // GET: Visualizador/Details/5
       [HttpGet]
        public IActionResult Categoria()
        {

            IList<ListModel> lstCategoria = new List<ListModel>();
            IList<geo_categoria> structCategoria = new List<geo_categoria>();
            var strucCategoria= categoria.CategoriasActivas();
            SelectList slCategoria = new SelectList(lstCategoria, "Id", "Text");
            ViewBag.slCategoria = slCategoria;

            return View();
        }

        // POST: Visualizador/Create

        [HttpPost]
        public JsonResult Create(int selectcategoria )
        {
            int  cat =secuencial.NumberSecuencial();

            IList<ListModel> lstCategoria = new List<ListModel>();
            var stfoto = foto.Getfoto(selectcategoria);

            if (stfoto != null) { 
              var lstgrupofoto = (from x in stfoto
                                  select new { id = x.id, Text =  x.url  , sec= cat });
                return Json(lstgrupofoto.ToArray());
            }
            return Json(null);
        }

        

        // GET: Visualizador/Edit/5
        [HttpPost]
        public ActionResult Update(int selectcategoria)
        {

            IList<ListModel> lstCategoria = new List<ListModel>();
            var stfoto = foto.Getfoto(selectcategoria);
     
            if (stfoto != null)
            {
                var lstgrupofoto = (from x in stfoto
                                    select new { id = x.id, Text = x.url});
                return Json(lstgrupofoto.ToArray());
            }
            return Json(null);
        }

      

        // GET: Visualizador/Delete/5
        public ActionResult _StreetView()
        {
            return View();
        }
        private IHostingEnvironment _Env;
        public VisualizadorController(IHostingEnvironment envrnmt)
        {
            _Env = envrnmt;
        }
        // GET: Visualizador/Edit/5
        [HttpPost]
        public ActionResult Save(int selectcategoria , int secuencial, int idimagen , string heading, string coordenadas , string pitch)
        {
            ValUsuario = HttpContext.Session.GetString("IsUsuario");

            if (ValUsuario != null)
            {
                DateTime localDate = DateTime.Now;
            geo_ubicacion geo = new geo_ubicacion();
            geo.geo_ubu_des ="ingreso";
            geo.id_img = idimagen;
            geo.id_sec = secuencial;
            geo.create_date = localDate;
            geo.create_usr = HttpContext.Session.GetString("IsUsuario");
            var webRootInfo = _Env.WebRootPath+"\\images\\"+ selectcategoria+"\\";
        
            var url = "https://maps.googleapis.com/maps/api/streetview?size=900x800&location="+coordenadas.Replace("(","").Replace(")", "") + "&heading="+heading + "&pitch=" + pitch + "&key=AIzaSyBNY6hecKQkIFeckd2pfUKk6zyE921VakM";
      
            var success=  geoUbicacion.Save(geo.geo_ubu_des, geo.id_img, geo.id_sec, Convert.ToDateTime(geo.create_date), geo.create_usr,  url);
            if (success == 1) {
                    return Json(1);
                }

            return Json(null);
            }
            else
            {
                return RedirectToAction("logout", "Login");

            }
        }
    }
}

MardisGeo/Views/Visualizador/Categoria.cshtml
@model MardisGeo.Views.modelWeb.ListModel

 


  
        
     

    @*@Html.DropDownListFor(model => model.Nombre, Model.ActionsList, new { @class = "form-control" })*@

    <div class="form-inline">
        <div class="form-group">
            <label>
                <input type='radio' name='geoCAT' value="1" id="1" hidden />
                <img src="~/images/comercial/c1.png" style="width:180px; height:98px; opacity: 1 ;background-color: rgba(152, 16, 152, 0.68) " class="imgcla" id="1m" />
            </label>
        </div>
        <div class="form-group">
            <label>
                <input type='radio' name='geoCAT' value="2" id="2" hidden />

                <img src="~/images/Oficinas/o2.png" style="width:180px; height:98px;" class="imgcla" id="2m" />
            </label>
        </div>
        <div class="form-group">
            <label>
                <input type='radio' name='geoCAT' value="3" id="3" hidden />
                
                <img src="~/images/Residencial/r2.png" style="width:180px; height:98px;" class="imgcla" id="3m" />
            </label>
        </div>
        <div class="form-group">
            <label>
           
                <input type='radio' name='geoCAT' value="4" id="4" hidden />
                <img src="~/images/Rural/rl2.png" style="width:180px; height:98px;" class="imgcla" id="4m" />
            </label>
        </div>
    </div>

MardisGeo/Views/Visualizador/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Principal.cshtml";
}


       

    
    @*<table>

           <tr>
               <td>
                <label>
                   <input type="radio" name="fb" value="big" id="1" />
                   <img src="~/images/logoMardis.png">
               </label>
               </td>
                 <td>
               <label>
                   <input type="radio" name="fb" value="big" id="1" />
                   <img src="~/images/logoMardis.png">
               </label>
                 </td>
               <td>
                   <label>
                       <input type="radio" name="fb" value="big"  id="1"/>
                       <img src= "~/images/Oficinas/myipss.png" />
                   </label>
               </td>
           </tr>
        </table>*@
 
 
 <div id="googgleApi">
   
     @Html.Partial("_StreetView")
        <div class="content-geo">
            <h1>CODIGO : <small><label id="idsec"></label></small></h1>

      
       
            <input type="text" hidden id="secid" value="0"/>
            <row>
                
                
            </row>
            <br>
            <div class="content-geo-imag">
                @Html.Partial("Categoria")
            </div>
            <div class="form-inline">
                   <div class="form-group">
                    <div class="col-sm-2 col-md-1 ">
                        <button type="submit" class="btn btn-success" id="idGuardar" disabled><span class="glyphicon glyphicon-floppy-disk"></span> Guardar</button>
                    </div>

                </div>
            </div>
            <div id="Divtb1">
                <hr class="lineMardis">
</div>
            <div id="Divtb">

                <div class="form-inline">
                   <table class='table_mardis' id='idtable'></table>
                </div>
            </div>  
</div>
   
   
</div>
    @section Scripts {


        <script type="text/javascript">

            $(document).ready(function () {
                var loca = '';
                var img = '';
                $('#1m').css({ 'opacity': '1' });
            });
       
            $("#idGuardar").click(function () {

                Save($('input:radio[name=geoCAT]:checked').val(), $("#secid").val().toString(), $('input:radio[name=geoimg]:checked').val())
            });

            function cambiar(x) {
                var idcategorias = x.id;

                var sec = $("#secid").val();
                
                if (sec==0){
                $("#idsec").empty();

                GenerarNuevoRegistroGeo(1)
                }
                $('.idmmardis').css({ 'background-color': 'transparent' });
                var imgids = '#' + idcategorias + 'mis'
                $(imgids).css({ 'background-color': '#a50000' });
            }
            function GenerarNuevoRegistroGeo(selectcategoria) {
                htmlimg = ""
                count = 0;
            
                $.ajax({
                    url: '@Url.Action("Create", "Visualizador")',
                 type: "POST",
                 content: "application/json; charset=utf-8",



                 data: {
                     selectcategoria
                 },
                 success: function (result) {
                     $("#idsec").append(result[0].sec)
                     $("#IdCat").prop('disabled', false);
                     $("#secid").val(result[0].sec)
                     $("#idGuardar").prop('disabled', false);
                  
                 },

                 error: function () {
                     $("#Divtb").append("<p> NO EXISTE FOTOS PARA ESA CATEGORIA</p > ")
                 }
             });
            }

            $('input:radio[name=geoCAT]').click(function () {
                selectcategoria = $('input:radio[name=geoCAT]:checked').val();
                idcategoria = $('input:radio[name=geoCAT]:checked').attr('id');
                $('.imgcla').css({ 'opacity': '1' });
                var imgid = '#' + idcategoria+'m'
                $(imgid).css({ 'opacity' : '0.6' });
                updateImage(selectcategoria)
            });
       


          

            function updateImage(selectcategoria) {
                count = 0;

                htmlimg = '';

                $.ajax({
                    url:'@Url.Action("Update", "Visualizador")',
                    type: "POST",
                    content: "application/json; charset=utf-8",



                    data: {
                        selectcategoria
                    },
                    success: function (result) {
                        $("#idtable").empty()
                        $("#idsec").append(result[0].sec)
                        $("#IdCat").prop('disabled', false);
                        $.each(result, function (index, value) {
                            count++
                            if (count == 1) { htmlimg += "" }

                            htmlimg += "<td class='tb_mardis'>"
                                + "<div class='idmmardis'  id=" + result[index].id + "mis>"
                                + "<label>"
                                + "<input type='radio' name='geoimg' value=" + (result[index].id) + " id=" + (result[index].id) + " onclick='cambiar(this)'; hidden/>" +
                                " <img src=" + result[index].text + " class='imgMardis' id=" + result[index].id + "mi >" +
                                " </label>" +
                                " </div>" +
                                "</td >"
                            if (count == 1) { htmlimg += ""; count = 0 }
                        });

                        $("#idtable").prepend(htmlimg)
                        $("#idtable").serialize()
                    },

                    error: function () {
                        $("#Divtb").append("<p> NO EXISTE FOTOS PARA ESA CATEGORIA</p > ")
                    }
                });


            }
         
            function Save(selectcategoria, secuencial, idimagen) {



                var scshop = 'ss';

                var coordenadas = panorama.getPosition() + '';
                var heading = panorama.getPov().heading + '';
                var pitch = panorama.getPov().pitch + '';

                if (idimagen !== undefined) {
                    $.ajax({
                        url: '@Url.Action("Save", "Visualizador")', 
                        type: "POST",
                        content: "application/json; charset=utf-8",



                        data: {
                            selectcategoria, secuencial, idimagen, heading, coordenadas, pitch
                        },
                        success: function (result) {
                            if (result == 1) {
                                $("#idsec").empty();
                                $("#idtable").empty();
                                $("#IdCat").prop('disabled', true);
                                $("#idGuardar").prop('disabled', true);
                                $("#secid").val(0);
                                $.toaster({
                                    priority: 'success',
                                    title: 'Aviso',
                                    message: "LA INFORMACION SE GUARDO CORRECTAMENTE",
                                    settings: {
                                        timeout: 5500
                                    }
                                });
                            } else {
                                bootbox.alert("Se registro  un error, comuniquese  con el administrador  ")

                            }

                        },
                        error: function () {
                            bootbox.alert("Se registro  un error, comuniquese  con el administrado  ")
                        }
                    });

                } else {
                    bootbox.alert("Seleccione  una imagen ")


                }
            }

     

        </script>
      


    }

MardisGeo/Views/Visualizador/_StreetView.cshtml
 
    <div id="map" style="width:20%; height:900px;"></div>
    <div id="pano" style="width:28%; height:900px;"></div>
    <script>
        var panorama;
        function initialize() {
            
            var fenway = { lat: -0.165888, lng: -78.479190 };
            var map = new google.maps.Map(document.getElementById('map'), {
                center: fenway,
                zoom: 14
            });
             panorama = new google.maps.StreetViewPanorama(
                document.getElementById('pano'), {
                    position: fenway,
                    pov: {
                        heading: 34,
                        pitch: 10
                    }
                });

            map.setStreetView(panorama);
            
        }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCZYA-xee_bKiCHQakUcDJtfVXagv_rhbA&callback=initialize">
    </script>